version: "3.9"

services:
    db:
        image: postgres:15
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_DB: IMV_book_catalog
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis
        container_name: redis-cache
        ports:
            - "6379:6379"

    webapi:
        build:
            context: .
            dockerfile: BookCatalogApi/Dockerfile
        container_name: bookcatalog-api
        depends_on:
            - db
            - redis
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConnectionStrings__BookCatalogConnection: "Host=db;Port=5432;Database=IMV_book_catalog;Username=postgres;Password=postgres"
            ConnectionStrings__RedisConnectionString: "redis:6379"
        ports:
            - "8080:80"
        networks:
            - backend

volumes:
    pgdata:

networks:
    backend:
